[15-Mar-2021 10:31:02 UTC] Uncaught exception: 'Exception' with message ' Wrong login, please try again'
Stack trace: #0 [internal function]: App\Controllers\Admin\Users->loginAction()
#1 C:\MAMP\htdocs\feedback\Core\Controller.php(22): call_user_func_array(Array, Array)
#2 C:\MAMP\htdocs\feedback\Core\Router.php(72): Core\Controller->__call('login', Array)
#3 C:\MAMP\htdocs\feedback\public\index.php(20): Core\Router->dispatch('admin/users/log...')
#4 {main}
Thrown inC:\MAMP\htdocs\feedback\App\Controllers\Admin\Users.php on line 25
[15-Mar-2021 10:31:11 UTC] Uncaught exception: 'Exception' with message ' Wrong login, please try again'
Stack trace: #0 [internal function]: App\Controllers\Admin\Users->loginAction()
#1 C:\MAMP\htdocs\feedback\Core\Controller.php(22): call_user_func_array(Array, Array)
#2 C:\MAMP\htdocs\feedback\Core\Router.php(72): Core\Controller->__call('login', Array)
#3 C:\MAMP\htdocs\feedback\public\index.php(20): Core\Router->dispatch('admin/users/log...')
#4 {main}
Thrown inC:\MAMP\htdocs\feedback\App\Controllers\Admin\Users.php on line 25
[15-Mar-2021 10:31:53 UTC] Uncaught exception: 'Exception' with message ' Wrong login, please try again'
Stack trace: #0 [internal function]: App\Controllers\Admin\Users->loginAction()
#1 C:\MAMP\htdocs\feedback\Core\Controller.php(22): call_user_func_array(Array, Array)
#2 C:\MAMP\htdocs\feedback\Core\Router.php(72): Core\Controller->__call('login', Array)
#3 C:\MAMP\htdocs\feedback\public\index.php(20): Core\Router->dispatch('admin/users/log...')
#4 {main}
Thrown inC:\MAMP\htdocs\feedback\App\Controllers\Admin\Users.php on line 25
